---
abstract: 'Mojolicious plugin to fill in form.'
author:
  - 'Uchiko <memememomo@gmail.com>'
build_requires:
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v1.1.0, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-FillInFormLite
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Mojolicious::Plugin::FillInFormLite:
    file: lib/Mojolicious/Plugin/FillInFormLite.pm
    version: 0.02
requires:
  HTML::FillInForm::Lite: 1.13
  Mojolicious: 0
  perl: 5.008005
resources:
  bugtracker: https://github.com/memememomo/Mojolicious-Plugin-FillInFormLite/issues
  homepage: https://github.com/memememomo/Mojolicious-Plugin-FillInFormLite
  repository: git://github.com/memememomo/Mojolicious-Plugin-FillInFormLite.git
version: 0.02
